### ISSUE TITLE
Error managent on the lib is based on api-server response syntax .. is it viable?

### ISSUE THREAD

**Issue by perki** [pryv/lib-javascript#10]
Today I made a fix on the lib f7e2c63b45d9cfa293240b9bbe4db76b63ff9ff9 to catch when response code is not the expected one. 

It may not be the good way to proceed to handle offline mode correctly. Offline or bad gateway may generate unexpected codes that should trigger a "keep this for later" and not be considered as error..

Discussion is now open..

**Comment by sgoumaz** [comment]
Closing (cleaning up old stuff)
