### ISSUE TITLE
Want full offline-mode functionality

### ISSUE THREAD

**Issue by sgoumaz** [pryv/lib-javascript#17]
Either implement full offline support if feasible and appropriate, which requires implementing reasonably functional business logic within the lib (e.g. for event type validation), or at least clearly document that aspect for users and plan steps towards improved support.

Misc. notes for design:
- Check out ServiceWorker API
- Some references: Hoodie, Firebase

**Comment by kschiess** [comment]
We will be removing offline support completely from this library. As this issue is not in line with that goal, closing it.
