### ISSUE TITLE
Would like the lib to use websockets for calling the backend when appropriate

### ISSUE THREAD

**Issue by sgoumaz** [pryv/lib-javascript#18]
Food for thought. In cases where the client already connects a websocket for live updates,  it seems natural to use it for backend calls too (removing the overhead of HTTP could also perceptibly improve performance). HTTP will still be needed for clients that don't need to maintain a connection.

(See http://bone.io for an example of framework relying purely on Socket.IO.)

**Comment by kschiess** [comment]
We decided not to pursue this.
