### ISSUE TITLE
[ERROR] 1475370663273 <userid> While fetching data API_UNREACHEABLE

### ISSUE THREAD

**Issue by roosemberth** [pryv/lib-javascript#32]
Hello,
I'm getting these errors on my software component for every request I try to do on pryv. 
The message is a wrapper defined in lib-node-bridge, but it is just a wrap for a request made on ConnectionEvents.js.
 
Stacktrace:
https://github.com/pryv/lib-node-bridge/blob/master/source/gateway/AccountContainer.js#L171-L172
https://github.com/pryv/lib-javascript/blob/master/source/connection/ConnectionEvents.js#L70
https://github.com/pryv/lib-javascript/blob/master/source/connection/ConnectionEvents.js#L49
https://github.com/pryv/lib-javascript/blob/master/source/connection/ConnectionEvents.js#L486-L490

**Comment by perki** [comment]
@roosemberth can you be more detailed. 
- a way to reproduce it.
- the full error message ..

**Comment by roosemberth** [comment]
The full error message is:
    [ERROR] 1475370663273 <userid> While fetching data API_UNREACHEABLE 

To reproduce it using nodejs:

```javascript
var SdkBridge        = require('pryv-sdk-bridge');
var pryvDb           = new SdkBridge.Database();
var pryv             = require('pryv');
var AccountContainer = SdkBridge.AccountContainer;

function cback(err){
	// middleware callback
}

pryvDb.forEachUser(function (pryvAcc, srvAcc) {
	if (<condition on srvAcc.username>){
		var connection = new pryv.Connection({
				username:   pryvAcc.user,
				auth:       pryvAcc.token,
				domain:     "<my pryv domain>"
		});
		var accountContainer = new AccountContainer(pryvAcc, srvAcc, connection);
		accountContainer.batchCreateEvents(events, cback);
	}
	// else do nothing
}

```

with events a valid object, ie: = [ { streamId: "existingStreamID", type: "validType", time: 1475402165.860 }, ...]

**Comment by pryvfish** [comment]
For 
domain: "<my pryv domain>"

You are using your own domain right?

**Comment by roosemberth** [comment]
I tryed looking into the log files on core, but I wasn't able to pin point the problem. I did make a copy for further analysis: 

api-server-console.log-1475417342
browser-server-console.log-1475417342

yes, for `domain` I'm using my pryv domain

**Comment by kebetsi** [comment]
API UNREACHABLE is a custom error of the lib-javascript. It appears when:
1. There is no **meta** field in the response
2. There is a error in the parsing of the response
3. There is a timeout
I will take a look at the log files.

**Comment by roosemberth** [comment]
I'm not logging the request been made to the core:

`/events?fromTime=%2C&toTime=1475556663.574&streams%5B%5D=emfit-val-period&streams%5B%5D=emfit-val-sleep&streams%5B
%5D=emfit-val-hrv&sortAscending=false`

**Comment by pryvfish** [comment]
I can see that the fromTime parameter is faulty. It might be a bug from the lib-javascript but anyway should not trigger an API_UNREACHABLE issue.

**Comment by kebetsi** [comment]
From what I read, `2C` is the URL encoded `,` (comma), so it doesn't make sense, but it should be an invalid parameters format error.

**Comment by roosemberth** [comment]
I managed to strip the bug, the bridge is working again. I'll make a résumé of the bug which was on my application itself

**Comment by roosemberth** [comment]
I was constructing a the pryv domain url using data comming from an external server. More precisely a unique identifier which was ended by a whitespace character. I stripped the space and it seems to be working now.

```
[ERROR] 1475590592029 test-dev-22345 While fetching data { id: 'API_UNREACHEABLE',
  message: 'Error on request ',
  details: 'ERROR: getaddrinfo ENOTFOUND test-dev-22345%20.domocare.io test-dev-22345%20.domocare.io:443\nRequest: GET https://test-dev-22345%20.domocare.io:443/events?fromTime=%20&toTime=1475590592.816&streams%5B%5D=emfit-val-period&streams%5B%5D=emfit-val-sleep&streams%5B%5D=emfit-val-hrv&sortAscending=false' }
