### ISSUE TITLE
As a Pryv-dev, I need the test environment to always be in a stable state, even in case of errors.

### ISSUE THREAD

**Issue by tmodoux** [pryv/lib-javascript#37]
Current test-suite seems to leave the Pryv test account (libjs-test-pryv.pryv.me) in an unstable state when some tests crash. This makes the next run of the test suite erroneous as well (missing/already existing streams when trying to delete/create inside beforeAll/afterAll).

Consider improving test environment cleaning and setup via before/after or using batchcall.

**Comment by kschiess** [comment]
Work on this is ongoing.
