### ISSUE TITLE
Need implementation code to undergo a thorough review

### ISSUE THREAD

**Issue by sgoumaz** [pryv/lib-javascript#8]
Vs [guidelines](http://pryv.github.io/guidelines), on issues such as consistency of names (also against the backend API), of the order of declarations, of return values; clean-up code documentation, etc.

Expected result: satisfactorily refactored code and/or planned issues to fix problems.

**Comment by kschiess** [comment]
We've performed one such review this year. We'll continue to improve the code in lib-javascript on an ongoing basis.
