### ISSUE TITLE
Need the tests to be rewritten for clarity

### ISSUE THREAD

**Issue by sgoumaz** [pryv/lib-javascript#9]
- All tests must follow the usual test structure (see: [guidelines](http://pryv.github.io/guidelines/code-javascript.html))
- "Acceptance" tests (= exposed API) go into `acceptance` subfolder, unit tests (= internal implementation) go into `unit`
- Tests doing API calls must consistently use requests recording/replay (either via node-replay or nock)
- Test coverage must be automated (e.g. with blanket)
- Existing tests that contradict the desired API (meaning the API must change) must be flagged with a TODO
- Unimplemented tests must be added for currently uncovered/unimplemented bits of the desired API

**Comment by kschiess** [comment]
Copied this information elsewhere; closing this, as it isn't actionable for us in this form.
